const backgroundWindow=overwolf.windows.getMainWindow(),eventEmitter=backgroundWindow.eventEmitter,db=backgroundWindow.db;var activeGameTicker=null;function loadLatestSessions(){db.getSessions(function(l){let d=document.querySelector("#sessionStats"),m=document.querySelector("#summaryStats"),c=document.querySelector("#topGameTitle"),u=document.querySelector("#topGameTime"),g=document.querySelector("#gameStarts"),f=document.querySelector("#weekSummaryText");if(d.innerHTML="",g.innerHTML="",f.innerHTML="",m.innerHTML="",0==l.length){let e=document.createElement("tr");e.innerHTML='<td colspan="3" class="text-center" style="height: 305px; vertical-align: middle;"><em>No played games so far</em></td>',d.appendChild(e),m.appendChild(e),g.innerHTML="<em>You have not played any games yet</em>",f.innerHTML="No data tracked yet, play some games! :)",c.innerHTML=shorten("No games played yet",45),u.innerHTML="",renderGraph(null)}else{let t=!0,n={},a=0;for(var p of l){if(a<10){let e=document.createElement("tr");e.innerHTML=`
        <td>${shorten(p.gameTitle,40)}</td>
        <td class="text-right" style="width: 150px;">${formatTimespan(p.startDate,p.endDate,t)}</td>
        <td class="text-center" style="width: 120px;">${formatDate(new Date(p.startDate))}</td>`,d.appendChild(e),t=!1}n[p.gameTitle]||(n[p.gameTitle]={gameTitle:p.gameTitle,startCount:0,sessions:[]}),n[p.gameTitle].startCount++,n[p.gameTitle].sessions.push(p),a++}if(a<10){let e=document.createElement("tr");e.innerHTML=`
<td colspan="3" rowspan="${10-a}" class="text-center" style="vertical-align: middle; height: ${31*(10-a)}px;">
  <em>Play more games to fill this area!</em>
</td>`,d.appendChild(e)}var y,T=sortDictionaryByProperty(n,"startCount",!1);let e={},i=0;for(y of T){var h=y[1];if(i<10){let e=document.createElement("div");e.innerHTML=`<span class="badge badge-secondary">${h.startCount}</span> ${shorten(h.gameTitle,30)}`,g.appendChild(e)}e[y[0]]={gameTitle:h.gameTitle,totalTime:y[1].sessions.map(function(e){return getTimeDifference(e.startDate,e.endDate)}).reduce(function(e,t){return e+t},0)},i++}var D,w=sortDictionaryByProperty(e,"totalTime",!1);c.innerHTML=shorten(w[0][1].gameTitle,45),u.innerHTML=`Played: ${outputTimesObjectFromDifference(w[0][1].totalTime)}`;for(D of sortDictionaryByPropertyAlphabetically(n,"gameTitle",!0)){let e=D[1];var v=e.sessions.map(e=>getTimeDifference(e.startDate,e.endDate)).reduce((e,t)=>e+t);let t=document.createElement("tr");t.innerHTML=`
        <td>${shorten(e.gameTitle,50)}</td>
        <td class="text-right" style="width: 60px;">${e.startCount}</td>
        <td class="text-right" style="width: 120px;">${outputTimesObjectFromDifference(v)}</td>`,m.appendChild(t)}window.gameStartItems=n;let r=Object.keys(n).flatMap(function(e){return n[e].sessions}),s=new NDate(Date.now()).removeTime().addDay(-6);var L=r.filter(e=>e.startDate>=s.timestamp).map(e=>getTimeDifference(e.startDate,e.endDate)).reduce((e,t)=>e+t),l=getTimeObject(L),T=1<=l.days?`${pluralize(l.days,"day","days")} and `:"",w=1<=l.hours?`${pluralize(l.hours,"hour","hours")} and `:"",L=1<=l.minutes?`${pluralize(l.minutes,"minute","minutes")}`:"";let o="";L||w||(o=pluralize(l.minutes,"second","seconds")),f.innerHTML=`The last 7 days you spent ${T}${w}${L}${o} in-game.`,renderGraph(r)}})}function renderGraph(r){let s={labels:["Day 1","Day 2","Day 3","Day 4","Day 5","Day 6","Day 7"],series:[[0,0,0,0,0,0,0]]};for(let e=0;e<7;e++){var t=new NDate(Date.now()).removeTime().addDay(e-6);s.labels[e]=formatDate(t.date)}if(r&&null!==r)for(let i=0;i<7;i++){let e=new NDate(Date.now()).removeTime().addDay(i-6),t=e.timestamp,n=e.addDay(1).timestamp;var o=r.filter(e=>e.startDate>=t&&e.startDate<=n).map(e=>getTimeDifference(e.startDate,e.endDate));let a=0;0<o.length&&(o=o.reduce((e,t)=>e+t),a=o/3600),s.series[0][i]=a}else;setTimeout(function(){new Chartist.Bar("#weekSummaryGraph",s,{axisY:{offset:45,labelInterpolationFnc:e=>e<1?`${(60*e).toFixed(0)}min`:`${e}hrs`},height:149})},200)}eventEmitter.addEventListener("game-launched",function(){activeGameTicker=setInterval(loadLatestSessions,5e3),loadLatestSessions()}),eventEmitter.addEventListener("refresh-window",function(e){"mainWindow"==e&&loadLatestSessions()}),eventEmitter.addEventListener("game-exited",function(){null!=activeGameTicker&&(clearInterval(activeGameTicker),activeGameTicker=null,loadLatestSessions())}),loadLatestSessions(),overwolf.windows.getCurrentWindow(function(e){new DraggableWindow(e.window,document.getElementById("titleBar")),document.getElementById("exitButton").addEventListener("click",function(){overwolf.games.getRunningGameInfo(function(e){e||(log("[Exit]","No games are running, exiting application"),eventEmitter.emit("shutdown",null))}),overwolf.windows.close(e.window.id,function(){})}),overwolf.extensions.current.getManifest(function(e){document.getElementById("titleBarName").innerHTML=`Game Time Tracker - v${e.meta.version}`})});