const backgroundWindow=overwolf.windows.getMainWindow(),eventEmitter=backgroundWindow.eventEmitter,db=backgroundWindow.db;var activeGameTicker=null;function loadLatestSessions(){db.getSessions(function(m){let c=document.querySelector("#sessionStats"),u=document.querySelector("#summaryStats"),g=document.querySelector("#topGameTitle"),f=document.querySelector("#topGameTime"),T=document.querySelector("#gameStarts"),p=document.querySelector("#weekSummaryText");if(c.innerHTML="",T.innerHTML="",p.innerHTML="",u.innerHTML="",0==m.length){let e=document.createElement("tr");e.innerHTML='<td colspan="3" class="text-center" style="height: 305px; vertical-align: middle;"><em>No played games so far</em></td>',c.appendChild(e),u.appendChild(e),T.innerHTML="<em>You have not played any games yet</em>",p.innerHTML="No data tracked yet, play some games! :)",g.innerHTML=shorten("No games played yet",45),f.innerHTML="",renderGraph(null)}else{let t=!0,n={},a=0;for(var y of m){if(a<10){let e=document.createElement("tr");e.innerHTML=`
        <td>${shorten(y.gameTitle,40)}</td>
        <td class="text-right" style="width: 150px;">${formatTimespan(y.startDate,y.endDate,t)}</td>
        <td class="text-center" style="width: 120px;">${formatDate(new Date(y.startDate))}</td>`,c.appendChild(e),t=!1}n[y.gameTitle]||(n[y.gameTitle]={gameTitle:y.gameTitle,startCount:0,sessions:[]}),n[y.gameTitle].startCount++,n[y.gameTitle].sessions.push(y),a++}if(a<10){let e=document.createElement("tr");e.innerHTML=`
<td colspan="3" rowspan="${10-a}" class="text-center" style="vertical-align: middle; height: ${31*(10-a)}px;">
  <em>Play more games to fill this area!</em>
</td>`,c.appendChild(e)}var h,m=sortDictionaryByProperty(n,"startCount",!1);let e={},i=0;for(h of m){var D=h[1];if(i<10){let e=document.createElement("div");e.innerHTML=`<span class="badge badge-secondary">${D.startCount}</span> ${shorten(D.gameTitle,30)}`,T.appendChild(e)}e[h[0]]={gameTitle:D.gameTitle,totalTime:h[1].sessions.map(function(e){return getTimeDifference(e.startDate,e.endDate)}).reduce(function(e,t){return e+t},0)},i++}m=sortDictionaryByProperty(e,"totalTime",!1);g.innerHTML=shorten(m[0][1].gameTitle,45),f.innerHTML=`Played: ${outputTimesObjectFromDifference(m[0][1].totalTime)}`;var w,m=sortDictionaryByPropertyAlphabetically(n,"gameTitle",!0);console.log(m);for(w of m){let e=w[1];var v=e.sessions.map(e=>getTimeDifference(e.startDate,e.endDate)).reduce((e,t)=>e+t);let t=document.createElement("tr");t.innerHTML=`
        <td>${shorten(e.gameTitle,50)}</td>
        <td class="text-right" style="width: 60px;">${e.startCount}</td>
        <td class="text-right" style="width: 120px;">${outputTimesObjectFromDifference(v)}</td>`,u.appendChild(t)}window.gameStartItems=n;let r=Object.keys(n).flatMap(function(e){return n[e].sessions}),s=new NDate(Date.now()).removeTime().addDay(-6);m=r.filter(e=>e.startDate>=s.timestamp).map(e=>getTimeDifference(e.startDate,e.endDate)).reduce((e,t)=>e+t),m=getTimeObject(m);let o="";m.hours&&1===m.hours?o=`${m.hours} hour and `:1<m.hours&&(o=`${m.hours} hours and `);let l="";m.minutes&&1===m.minutes?l=`${m.minutes} minute`:1<m.minutes&&(l=`${m.minutes} minutes`);let d="";""==l&&""==o&&(1==m.seconds?d="one second":1<m.seconds&&(d=`${m.seconds} seconds`)),p.innerHTML=`The last 7 days you spent ${o}${l}${d} in-game.`,renderGraph(r)}})}function renderGraph(r){let s={labels:["Day 1","Day 2","Day 3","Day 4","Day 5","Day 6","Day 7"],series:[[0,0,0,0,0,0,0]]};for(let e=0;e<7;e++){var t=new NDate(Date.now()).removeTime().addDay(e-6);s.labels[e]=formatDate(t.date)}if(r&&null!==r)for(let i=0;i<7;i++){let e=new NDate(Date.now()).removeTime().addDay(i-6),t=e.timestamp,n=e.addDay(1).timestamp;var o=r.filter(e=>e.startDate>=t&&e.startDate<=n).map(e=>getTimeDifference(e.startDate,e.endDate));let a=0;0<o.length&&(o=o.reduce((e,t)=>e+t),a=o/3600),s.series[0][i]=a}else;setTimeout(function(){new Chartist.Bar("#weekSummaryGraph",s,{axisY:{offset:45,labelInterpolationFnc:e=>e<1?`${(60*e).toFixed(0)}min`:`${e}hrs`},height:149})},200)}eventEmitter.addEventListener("game-launched",function(){activeGameTicker=setInterval(loadLatestSessions,5e3),loadLatestSessions()}),eventEmitter.addEventListener("refresh-window",function(e){"mainWindow"==e&&loadLatestSessions()}),eventEmitter.addEventListener("game-exited",function(){null!=activeGameTicker&&(clearInterval(activeGameTicker),activeGameTicker=null,loadLatestSessions())}),loadLatestSessions(),overwolf.windows.getCurrentWindow(function(e){new DraggableWindow(e.window,document.getElementById("titleBar")),document.getElementById("exitButton").addEventListener("click",function(){overwolf.games.getRunningGameInfo(function(e){e||(log("[Exit]","No games are running, exiting application"),eventEmitter.emit("shutdown",null))}),overwolf.windows.close(e.window.id,function(){})}),overwolf.extensions.current.getManifest(function(e){document.getElementById("titleBarName").innerHTML=`Game Time Tracker - v${e.meta.version}`})});